books = [
    ("Antifragile", "https://amzn.to/4d9rD3E"),
    ("The Black Swan", "https://amzn.to/3xFx2yS"),
    ("Fooled by Randomness", "https://amzn.to/3xTxERI"),
    ("Skin in the Game", "https://amzn.to/4d0rL5r"),
    ("Full Incerto - all Taleb books in one", "https://amzn.to/3W1TsEO"),
    ("The Software Engineer's Guidebook", "https://amzn.to/3Q8C0e3"),
    ("Understanding Distributed Systems", "https://amzn.to/4d3hgOD"),
    ("Fundamentals of Software Architecture", "https://amzn.to/3UBWwqd"),
    ("Software Architecture - the Hard Parts", "https://amzn.to/3UrBR7V"),
    ("Thinking in Systems", "https://amzn.to/4aIMLvQ"),
    ("System Design Interview - Volume 1", "https://amzn.to/448eHGU"),
    ("System Design Interview - Volume 2", "https://amzn.to/4aIOTDJ"),
    ("Surely You're Joking, Mr Feynman!", "https://amzn.to/4b6SYBF"),
    ("What Do You Care What Other People Think?", "https://amzn.to/445WA4z"),
    ("Continuous Delivery", "https://amzn.to/4aH08g8"),
    ("Leonardo da Vinci - Biography", "https://amzn.to/3Ugho4W"),
    ("How to Think Like Leonardo da Vinci", "https://amzn.to/3U8m6RZ"),
    ("Boyd: The Fighter Pilot Who Changed the Art of War", "https://amzn.to/4473vKA"),
    ("The Mind of War: John Boyd and American Security", "https://amzn.to/3xHSWBQ"),
    ("Certain to Win: The Strategy of John Boyd, Applied to Business", "https://amzn.to/3JsZ7Mz"),
    ("Science, Strategy and War (Strategy and History)", "https://amzn.to/4b3GN8B"),
    ("Implementing Lean Software Development", "https://amzn.to/3wkfzvx"),
    ("Lean Startup", "https://amzn.to/3JCSNSJ"),
    ("Steal Like An Artist", "https://amzn.to/3WpTpCG"),
    ("Show Your Work", "https://amzn.to/4dk2Dqc"),
    ("Keep Going", "https://amzn.to/3JEkBpW"),
    ("Staff Engineer: Leadership beyond the management track", "https://amzn.to/49HqvB3"),
    ("The Staff Engineer's Path", "https://amzn.to/4b2Ei6y"),
    ("Public Relations", "https://amzn.to/3Ux6qt1")
]