books = [
    ("Mastery", "https://amzn.to/3WFYozD"),
    ("Clean Code", "https://amzn.to/3WHeDvY"),
    ("Tidy First", "https://amzn.to/3UTDxrb"),
    ("Professional Javascript for Web Developers", "https://amzn.to/4bdfyc0"),
    ("Atomic Habits", "https://amzn.to/3UTzj2G"),
    ("Creativity Inc", "https://amzn.to/3KlMjbt"),
    ("Influence", "https://amzn.to/3X5lJLh"),
    ("Thinking Fast and Slow", "https://amzn.to/3Ko17pT"),
    ("The Charisma Myth", "https://amzn.to/3VnwxmL"),
    ("The Goal", "https://amzn.to/3R56bTF"),
    ("Project Phoenix", "https://amzn.to/3Km7vhc"),
    ("The Laws of Human Nature", "https://amzn.to/3yIWcNT"),
    ("Shackleton's Way", "https://amzn.to/3R8tQCL"),
]